### ISSUE TITLE
Async Support

### ISSUE THREAD

**Issue by yilativ** [mtamme/NProxy#4]
Hi, 
I was wondering if you have examples of how you'd set up the NProxy to work with the async methods?

Thanks

**Comment by mtamme** [comment]
Hi,

there is nothing special about async method interception. For class based proxies you have to make the async method virtual:

```csharp
public class Async : IAsync
{
    public virtual async Task Invoke()
    {
        ...
    }
}

var proxy = proxyFactory.CreateProxy<Async>(Type.EmptyTypes, new MyInvocationHandler());
```

but I would recommend to use an interface based approach:

```csharp
public interface IAsync
{
    Task Invoke();
}

var proxy = proxyFactory.CreateProxy<IAsync>(Type.EmptyTypes, new MyInvocationHandler());
```
Cheers,
Martin

**Comment by mtamme** [comment]
Hi,

you can also find some unit tests in `Source/Test/NProxy.Core.Test/ProxyFactoryTestFixture.cs`. Look for `CreateProxyFromInterfaceWithAsyncReturnValueTest`, `CreateProxyFromAbstractClassWithAsyncReturnValueTest` and `CreateProxyFromClassWithAsyncReturnValueTest`.

Cheers,
Martin

PS: I will close your question now.
